### ISSUE TITLE
Revisit device_params and driver_params

### ISSUE THREAD

**Issue by broskoTT** [tenstorrent/tt-umd#106]
See out of these four which are hardware specific and not compiler specific (what cannot be changed vs what can)
    virtual void set_device_l1_address_params
    virtual void set_device_dram_address_params
    virtual void set_driver_host_address_params
    virtual void set_driver_eth_interface_params
    
My guess is many of these can be reduced or removed.

**Comment by blozano-tt** [comment]
My PR #234 addresses one of these.

**Comment by blozano-tt** [comment]
https://github.com/tenstorrent/tt-umd/pull/260
