### ISSUE TITLE
API tests

### ISSUE THREAD

**Issue by broskoTT** [tenstorrent/tt-umd#154]
A plan is to have a set of API tests:

- To showcase UMD usage to clients
- Which is arch agnostic
- Which showcases (like this simplest one) how cumbersome is the current minimal UMD setup.

A lot of stuff should be taken from existing tests.
At this point it seems harder to rewrite existing tests rather than starting a new one.

The tests should also somewhat follow code examples shown in this diagram: https://docs.google.com/drawings/d/1-m1azdsBqMA0A6ATYRMfkhyeuOJuGCEI62N5a96LXj0/edit

**Comment by pjanevskiTT** [comment]
Closing this since we have initial API tests, following tests need to be added together with new features...
