### ISSUE TITLE
Why specify C compiler if there is no C code in the project?

### ISSUE THREAD

**Issue by blozano-tt** [tenstorrent/tt-umd#198]
https://github.com/tenstorrent/tt-umd/blob/6deb8d7d2c6513af090d91c58e3ace53b4564b4e/CMakeLists.txt#L10

**Comment by pjanevskiTT** [comment]
@blozano-tt status?

**Comment by blozano-tt** [comment]
Its possible some of the dependencies have C code.

Lets just leave it until it becomes a problem.
