### ISSUE TITLE
Document in README how to build with gcc or clang

### ISSUE THREAD

**Issue by blozano-tt** [tenstorrent/tt-umd#199]
Is it still possible to build UMD using gcc (not clang) ?  If yes, can you add instructions to README? Only if it is easy to add, don't want to spam your PR if you don't know or if it isn't currently supported.

_Originally posted by @broskoTT in https://github.com/tenstorrent/tt-umd/pull/192#discussion_r1810159109_

**Comment by blozano-tt** [comment]
I have filed this as an issue, because Ideally we should investigate not forcing clang as default.

This will impact what we document.

**Comment by broskoTT** [comment]
Added in https://github.com/tenstorrent/tt-umd/pull/174
