### ISSUE TITLE
Install Additional files needed for running UMD

### ISSUE THREAD

**Issue by blozano-tt** [tenstorrent/tt-umd#201]
Not sure if you're aware, but for proper functioning of our UMD lib, there are some additional files needed apart from built artefacts.
create-ethernet-map binary is also needed (currently explicitly called by tt_metal client, but in near future called from the lib).
Also several soc_descriptor yaml files are needed for tests, which will probably also move to umd lib as well (not just tests).

_Originally posted by @broskoTT in https://github.com/tenstorrent/tt-umd/pull/192#discussion_r1810191646_

**Comment by broskoTT** [comment]
We removed the need to have create-ethernet-map.
We will move towards having const SoCDescriptors in code rather than .yaml.
There won't be a need for shipping additional files alongside libdevice.
We will reopen if this changes.
