### ISSUE TITLE
create-eth-map for Blackhole not working

### ISSUE THREAD

**Issue by pjanevskiTT** [tenstorrent/tt-umd#241]
Introduced by #235, create-eth-map binary is not working fully as expected. Chips section of the cluster descriptor is empty, it doesn't show any chips. The binary still works for Wormhole (Grayskull not tested)

I am not really sure how this is built from source, but I know tt-debuda has a binary in their own repo, which I have tested and it produced valid results. This binary is for Blackhole only, so we couldn't reuse it as a general binary, but maybe we could replicate their way of using these binaries

For reference, I am attaching three files (txt files to be able to upload it here)

1. cluster descriptor that binary from tt-debuda produces - 
[cluster_debuda.txt](https://github.com/user-attachments/files/17598278/cluster_debuda.txt)
2. cluster descriptor that we have used as a hardcoded for blackhole so far - https://github.com/tenstorrent/tt-umd/blob/main/blackhole_1chip_cluster.yaml
3. cluster descriptor that updated binary in tt-umd produces - 
[cluster_umd.txt](https://github.com/user-attachments/files/17598279/cluster_umd.txt)

**Comment by TTDRosen** [comment]
Hey! That's operating as expected i.e. consistent with GS. Between the debuda version and the release the decision was made to remove coordiantes from Blackhole so there was nothing for me to put into the chips field. This is consistent with Grayskull which also doesn't have coordinates.

**Comment by broskoTT** [comment]
I've reopened issue. But not with the task to fix CEM, rather to fix yaml parsing in tt_ClusterDescriptor.
This might unlock also not having specific grayskull codepath.

**Comment by abhullar-tt** [comment]
I  started some changes in `abhullar/bh-cluster-desc` to parse a cluster desc yaml when chips map is empty

**Comment by pjanevskiTT** [comment]
As per offline chat with @abhullar-tt , I will take over the work on the branch she mentioned above

**Comment by broskoTT** [comment]
@pjanevskiTT please raise a warning in code in this case
boardtype: {
   0: null,
}

I see that current bh CEM outputs that. We should probably resolve it, but not critical at the moment.

@TTDRosen any ideas why do we get this?

**Comment by abhullar-tt** [comment]
It’s because some machines are running old FW

**Comment by broskoTT** [comment]
Also, once this is resolved I think we can remove tt_ClusterDescriptor::create_for_grayskull_cluster
