### ISSUE TITLE
Non REG_TLB address concatenated to 32bit

### ISSUE THREAD

**Issue by broskoTT** [tenstorrent/tt-umd#281]
As reported by Luka and @tt-vjovanovic from tt-debuda team, reads/writes to regions of virtual addresses which sit above 32bits won't work. Specifically, they used this path for ARC.

Original message:
0x880030060
0x880030064
0x880030068
....
0x810000000
0x880000000
First three are scratch registers.
Last two are CSM memory and ROM
size = 1
core = 0,10
fallback_tlb = "LARGE_WRITE_TLB"
![Image](https://github.com/user-attachments/assets/dfe27943-9ada-4c9d-bcbe-4d6b5cf6fa13)

**Comment by joelsmithTT** [comment]
Should be fixed in https://github.com/tenstorrent/tt-umd/pull/328 FYI @tt-vjovanovic
