### ISSUE TITLE
Allow passing option for TensixSoftResetOptions to deassert_risc_reset_at_core

### ISSUE THREAD

**Issue by abhullar-tt** [tenstorrent/tt-umd#287]
syseng runs FW out of risc0 on active ethernet cores on BH. Metal wants to use risc1 and to enable this we need to deassert risc1 from host via `deassert_risc_reset_at_core` 

`TENSIX_DEASSERT_SOFT_RESET` is used to reset specific cores but this only resets risc0. Could the API be updated to allow passing a specified deassert value?

**Comment by broskoTT** [comment]
As far as I see, the send_tensix_risc_reset_to_core function accepts a value for which riscs to reset. At by default, the deassert_risc_reset_at_core sends this value:
static constexpr TensixSoftResetOptions TENSIX_DEASSERT_SOFT_RESET = TensixSoftResetOptions::NCRISC |
                                                                 ALL_TRISC_SOFT_RESET |
                                                                 TensixSoftResetOptions::STAGGERED_START;

What is the exact ask here? Do we want to sometimes not reset all of the riscs on core, so you'd want to surface this option to the API level?
Sorry for my ignorance, what are risc0 and risc1, are these triscs?
