### ISSUE TITLE
Linter

### ISSUE THREAD

**Issue by broskoTT** [tenstorrent/tt-umd#47]
Add clang, or some other linter support.
Take a look at how metal does it.
In any case, make sure to be compatible with tt-metal.

**Comment by broskoTT** [comment]
We can use "yamllint", and it is already present in tt-metal's image.
"clang-format" is also present.
Figure out if there's a way to also do cmake-format.

**Comment by broskoTT** [comment]
Also make sure to check this https://yyz-gitlab.local.tenstorrent.com/tenstorrent/budabackend/-/issues/2660
Information from there can be used to reduce .clang-format, while maintaining the same rules. It's probably good to keep the same .clang-format rules as tt-metal for consistency.

**Comment by pjanevskiTT** [comment]
@broskoTT can we close this?
