### ISSUE TITLE
Remove Hugepage in favour of IOMMU

### ISSUE THREAD

**Issue by broskoTT** [tenstorrent/tt-umd#49]
Hugepage is a bit of a pain to setup, and can be circumvented if IOMMU is setup.

There are a lot of details by @joelsmithTT on this design doc: https://docs.google.com/document/d/1qH6I3hykK_xjo8HA5RlmPE7vsK_2Fx4bygfv7_F663s/edit

This issue might be further broken down into smaller chunks, as there might be a lot of tasks related to the actual switch on all fronts.

**Comment by pjanevskiTT** [comment]
Closing this as there is #257 with more details regarding IOMMU
