### ISSUE TITLE
API cleanup and refinement

### ISSUE THREAD

**Issue by broskoTT** [tenstorrent/tt-umd#50]
Copied from https://docs.google.com/document/d/1DoDwJgGzvXiifB2jL0VRb2WmSvtPPcStqq7cgbSU04c/edit

- Identify and remove unnecessary APIs in tt_device, tt_SiliconDevice classes
- Simplify and standardize remaining interfaces
- Opportunity for more consistency in argument order among IO-related methods
- Document API changes
- Maintain tt_device interface, for now – it’s what Metal expects

Also, #41 probably addresses a part of this.
See what needs to be done afterwards.

**Comment by pjanevskiTT** [comment]
This issue already has smaller issues in terms of redesign, or @broskoTT will open those, so closing this
