### ISSUE TITLE
Merge metal's umd improvements as a v1 API improvement

### ISSUE THREAD

**Issue by broskoTT** [tenstorrent/tt-umd#52]
tt-metal team have been working on their own branch, for faster development.

Given that tt-metal is the main consumer of UMD going forward, it is logical that tt-metal needs drive further progress of UMD as a component.

@vtangTT has worked recently on these improvements. The remaining task is to merge his outstanding work into umd main. When this is done, Buda likely won't build anymore on umd main, which is fine since Buda will not be actively developed anymore.

This includes #41 but also #40 for which additional changes in metal runtime are needed.

**Comment by pjanevskiTT** [comment]
@vtangTT should we close this issue, #41 is merged and #40 is closed?

**Comment by vtangTT** [comment]
yep just merged https://github.com/tenstorrent/tt-umd/pull/64 so can close
