### ISSUE TITLE
Harvesting

### ISSUE THREAD

**Issue by joelsmithTT** [tenstorrent/tt-umd#91]
From @abhullar-tt: "Throughout Metal and UMD we assume only rows are harvested. On BH columns will be harvested."

**Comment by abhullar-tt** [comment]
For initial support of column harvesting it seems like we need to:
- use create-eth-map utility on BH to discover harvesting masks
- uplift to interpret this as columns harvested on BH rather than rows 

@broskoTT is this a good time to uplift the soc desc to have all the coordinate translations?

**Comment by pjanevskiTT** [comment]
This has been partially solved with #202 , we just need integration of the changes inside tt_SiliconDevice

**Comment by broskoTT** [comment]
The only thing left now is #115 , right? We can close this issue?

**Comment by pjanevskiTT** [comment]
We can, I have smaller issues to address this
