### ISSUE TITLE
Allow more host memory channels for Blackhole

### ISSUE THREAD

**Issue by pjanevskiTT** [tenstorrent/tt-umd#93]
We should allow more than one host memory channel for Blackhole. Since we are considering moving to IOMMU (#49), this issue should be low prirority, unless tt-metal really needs it for Blackhole

For reference, we are forcing single host memory channel here https://github.com/tenstorrent/tt-umd/blob/main/device/tt_silicon_driver.cpp#L519

**Comment by abhullar-tt** [comment]
Metal uses multiple host memory channels to support fast-dispatch on multiple chips

**Comment by broskoTT** [comment]
Fixed by https://github.com/tenstorrent/tt-umd/pull/393
